server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/products_db
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      open-in-view: false

  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    enabled: true